In [21]:
import pandas as pd

In [22]:
data = pd.read_csv("./LoanData_Bondora.csv")

print(data.shape)

data

/tmp/ipykernel_35733/3511746091.py:1: DtypeWarning: Columns (34,38,80,82,83,89,90) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("./LoanData_Bondora.csv")

(179235, 112)

,ReportAsOfEOD,LoanId,LoanNumber,ListedOnUTC,BiddingStartedOn,BidsPortfolioManager,BidsApi,BidsManual,UserName,NewCreditCustomer,...,PreviousEarlyRepaymentsCountBeforeLoan,GracePeriodStart,GracePeriodEnd,NextPaymentDate,NextPaymentNr,NrOfScheduledPayments,ReScheduledOn,PrincipalDebtServicingCost,InterestAndPenaltyDebtServicingCost,ActiveLateLastPaymentCategory
0,2021-07-20,66AE108B-532B-4BB3-BAB7-0019A46412C1,483449,2016-03-23 16:07:19,2016-03-23 16:07:19,970,1150,5.0,BO965519,False,...,0.0,2019-10-28,2020-01-27,NaN,NaN,NaN,NaN,0.00,51.73,31-60
1,2021-07-20,D152382E-A50D-46ED-8FF2-0053E0C86A70,378148,2015-06-25 11:02:28,2015-06-25 11:02:28,1295,0,1705.0,BOA9K172A,False,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0.00,47.08,180+
2,2021-07-20,87342E13-66CB-483F-833A-007953E50C78,451831,2016-01-14 10:00:21,2016-01-14 10:00:21,2700,565,5835.0,BO7971663,True,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,259.67,1659.60,180+
3,2021-07-20,87227056-6BF9-410C-98D1-008F788E122A,349381,2015-03-24 15:55:44,2015-03-24 15:55:44,1115,0,385.0,BO76151K3,True,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0.00,215.05,180+
4,2021-07-20,2DDE6336-E466-4624-A337-00A0ED1A1468,443082,2015-12-17 10:12:00,2015-12-17 10:12:00,305,0,785.0,BOK423A63,True,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,180+
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179230,2021-07-20,D9E714C3-B9B8-4FD1-B1AD-FF55B3AE8A8F,323749,2015-03-02 07:07:05,2015-03-02 07:07:05,2000,0,0.0,BO6492A4A,True,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.00,18.38,180+
179231,2021-07-20,09999223-3D69-42E3-BAAA-FF7F312AB236,468598,2016-02-17 10:17:35,2016-02-17 10:17:35,6215,70,1155.0,BO542A57A,False,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,NaN
179232,2021-07-20,370193A5-D19C-4A99-97F7-FF95BEA52731,462572,2016-02-05 09:35:26,2016-02-05 09:35:26,430,0,1055.0,BO65A965,False,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,NaN
179233,2021-07-20,98D9FCCE-0FD7-420E-9F7F-FFA960669E8B,396046,2015-08-17 17:23:05,2015-08-17 17:23:05,3000,0,0.0,BO9577433,True,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,NaN
179234,2021-07-20,65C924CD-8AAF-4ECC-9C8F-FFB0C5722CBB,374840,2015-06-15 10:22:34,2015-06-15 10:22:34,0,0,1300.0,avo1007,False,...,2.0,2016-04-27,2017-04-27,NaN,NaN,NaN,NaN,0.00,2.64,180+

In [23]:
drop_cols = []

for column in data.columns: 
    num_nan = data[column].isna().sum()
    pct = (num_nan/data.shape[0])*100
    
    if pct > 30.0:
        
        drop_cols.append(column)
    
    print(f"{column}: {num_nan} ({pct} %)")

ReportAsOfEOD: 0 (0.0 %)
LoanId: 0 (0.0 %)
LoanNumber: 0 (0.0 %)
ListedOnUTC: 0 (0.0 %)
BiddingStartedOn: 0 (0.0 %)
BidsPortfolioManager: 0 (0.0 %)
BidsApi: 0 (0.0 %)
BidsManual: 0 (0.0 %)
UserName: 0 (0.0 %)
NewCreditCustomer: 0 (0.0 %)
LoanApplicationStartedDate: 0 (0.0 %)
LoanDate: 0 (0.0 %)
ContractEndDate: 76239 (42.53577705247301 %)
FirstPaymentDate: 0 (0.0 %)
MaturityDate_Original: 0 (0.0 %)
MaturityDate_Last: 0 (0.0 %)
ApplicationSignedHour: 0 (0.0 %)
ApplicationSignedWeekday: 0 (0.0 %)
VerificationType: 50 (0.027896337210924205 %)
LanguageCode: 0 (0.0 %)
Age: 0 (0.0 %)
DateOfBirth: 179235 (100.0 %)
Gender: 45 (0.025106703489831784 %)
Country: 0 (0.0 %)
AppliedAmount: 0 (0.0 %)
Amount: 0 (0.0 %)
Interest: 0 (0.0 %)
LoanDuration: 0 (0.0 %)
MonthlyPayment: 6690 (3.7325299188216587 %)
County: 179235 (100.0 %)
City: 179235 (100.0 %)
UseOfLoan: 0 (0.0 %)
Education: 50 (0.027896337210924205 %)
MaritalStatus: 50 (0.027896337210924205 %)
NrOfDependants: 143635 (80.13780790582197 %)
EmploymentStatus: 202 (0.11270120233213378 %)
EmploymentDurationCurrentEmployer: 1606 (0.8960303512148856 %)
EmploymentPosition: 179235 (100.0 %)
WorkExperience: 142713 (79.62339944765252 %)
OccupationArea: 91 (0.05077133372388205 %)
HomeOwnershipType: 1657 (0.9244846151700282 %)
IncomeFromPrincipalEmployer: 0 (0.0 %)
IncomeFromPension: 0 (0.0 %)
IncomeFromFamilyAllowance: 0 (0.0 %)
IncomeFromSocialWelfare: 0 (0.0 %)
IncomeFromLeavePay: 0 (0.0 %)
IncomeFromChildSupport: 0 (0.0 %)
IncomeOther: 0 (0.0 %)
IncomeTotal: 0 (0.0 %)
ExistingLiabilities: 0 (0.0 %)
LiabilitiesTotal: 0 (0.0 %)
RefinanceLiabilities: 0 (0.0 %)
DebtToIncome: 50 (0.027896337210924205 %)
FreeCash: 50 (0.027896337210924205 %)
MonthlyPaymentDay: 0 (0.0 %)
ActiveScheduleFirstPaymentReached: 0 (0.0 %)
PlannedPrincipalTillDate: 124771 (69.61307780288448 %)
PlannedInterestTillDate: 1974 (1.1013473930872877 %)
LastPaymentOn: 6725 (3.7520573548693057 %)
CurrentDebtDaysPrimary: 103011 (57.47259184869027 %)
DebtOccuredOn: 103011 (57.47259184869027 %)
CurrentDebtDaysSecondary: 96967 (54.10048260663375 %)
DebtOccuredOnForSecondary: 96967 (54.10048260663375 %)
ExpectedLoss: 2639 (1.4723686779925795 %)
LossGivenDefault: 2639 (1.4723686779925795 %)
ExpectedReturn: 2639 (1.4723686779925795 %)
ProbabilityOfDefault: 2639 (1.4723686779925795 %)
DefaultDate: 107819 (60.15510363489274 %)
PrincipalOverdueBySchedule: 14843 (8.28130666443496 %)
PlannedPrincipalPostDefault: 107820 (60.155661561636954 %)
PlannedInterestPostDefault: 107820 (60.155661561636954 %)
EAD1: 107821 (60.15621948838118 %)
EAD2: 107821 (60.15621948838118 %)
PrincipalRecovery: 107820 (60.155661561636954 %)
InterestRecovery: 107820 (60.155661561636954 %)
RecoveryStage: 67295 (37.54568025218289 %)
StageActiveSince: 60488 (33.74787290428767 %)
ModelVersion: 2639 (1.4723686779925795 %)
Rating: 2733 (1.5248137919491171 %)
EL_V0: 174666 (97.45083270566575 %)
Rating_V0: 174666 (97.45083270566575 %)
EL_V1: 166311 (92.7893547577203 %)
Rating_V1: 166311 (92.7893547577203 %)
Rating_V2: 154092 (85.97204787011465 %)
Status: 0 (0.0 %)
Restructured: 0 (0.0 %)
ActiveLateCategory: 104251 (58.164421011521185 %)
WorseLateCategory: 52329 (29.195748598209054 %)
CreditScoreEsMicroL: 30304 (16.907412056796943 %)
CreditScoreEsEquifaxRisk: 167016 (93.18269311239435 %)
CreditScoreFiAsiakasTietoRiskGrade: 137407 (76.66304014282925 %)
CreditScoreEeMini: 74138 (41.36357296286997 %)
PrincipalPaymentsMade: 0 (0.0 %)
InterestAndPenaltyPaymentsMade: 0 (0.0 %)
PrincipalWriteOffs: 103085 (57.513878427762435 %)
InterestAndPenaltyWriteOffs: 103085 (57.513878427762435 %)
PrincipalBalance: 0 (0.0 %)
InterestAndPenaltyBalance: 5232 (2.919072725751109 %)
NoOfPreviousLoansBeforeLoan: 9 (0.005021340697966357 %)
AmountOfPreviousLoansBeforeLoan: 9 (0.005021340697966357 %)
PreviousRepaymentsBeforeLoan: 62386 (34.80681786481435 %)
PreviousEarlyRepaymentsBefoleLoan: 120350 (67.14648366669456 %)
PreviousEarlyRepaymentsCountBeforeLoan: 9 (0.005021340697966357 %)
GracePeriodStart: 137350 (76.63123831840879 %)
GracePeriodEnd: 137350 (76.63123831840879 %)
NextPaymentDate: 113614 (63.38828911763885 %)
NextPaymentNr: 66944 (37.3498479649622 %)
NrOfScheduledPayments: 66944 (37.3498479649622 %)
ReScheduledOn: 116191 (64.82606633748989 %)
PrincipalDebtServicingCost: 103085 (57.513878427762435 %)
InterestAndPenaltyDebtServicingCost: 103085 (57.513878427762435 %)
ActiveLateLastPaymentCategory: 96967 (54.10048260663375 %)

As we can see, there are a lot of missing values.

As such, we will drop all column with over 30% missing values.

In [24]:
data = data.drop(drop_cols, axis = 1)

data.shape

(179235, 69)

In [25]:
cols_const = []

for column in data.columns:
    if len(data[column].unique()) == 1:
        print(column)
        cols_const.append(column)

print(len(cols_const))

ReportAsOfEOD
1

In [26]:
data = data.drop(cols_const, axis = 1)

data.shape

(179235, 68)

We also dropped "ReportAsOfEOD" as that column was constant.

Besides those columns, there are some other columns that provide no usefull information.

We will also drop these columns.

In [19]:
drop_cols_2 = ['LoanId', 'LoanNumber', 'ListedOnUTC', 'BiddingStartedOn',
            'UserName', 'LanguageCode','LoanApplicationStartedDate',
            'LoanApplicationStartedDate','ApplicationSignedHour', 'ApplicationSignedWeekday',
            'ActiveScheduleFirstPaymentReached','ModelVersion','WorseLateCategory',
            'ProbabilityOfDefault', 'ExpectedLoss', 'LossGivenDefault', 'ExpectedReturn',
            'LoanDate', 'MaturityDate_Original' , 'MaturityDate_Last' ,'LastPaymentOn']

data = data.drop(drop_cols_2, axis = 1)

data.shape

(179235, 44)

In [28]:
print(data["LoanDate"][:250])

0      2016-03-23
1      2015-06-25
2      2016-01-19
3      2015-03-27
4      2015-12-22
          ...
245    2016-03-14
246    2016-02-17
247    2015-08-21
248    2015-02-24
249    2016-03-14
Name: LoanDate, Length: 250, dtype: object

In [33]:
print(data["Status"][200:300])

200     Repaid
201       Late
202     Repaid
203     Repaid
204       Late
        ...
295    Current
296     Repaid
297       Late
298     Repaid
299       Late
Name: Status, Length: 100, dtype: object